0x0.st is NOT a platform for:
    * piracy
    * pornography and gore
    * extremist material of any kind
    * terrorist content
    * malware / botnet C&C
    * anything related to crypto currencies
    * backups
    * CI build artifacts
    * other automated mass uploads
    * doxxing, database dumps containing personal information
    * anything illegal under German law

Uploads found to be in violation of these rules will be removed,
and the originating IP address may be blocked from further uploads.

Note that Tor exit nodes are blocked by the firewall due to frequent
rule violations.

read more on https://0x0.st/