name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -r ${{ matrix.os == 'macos-latest' && 'osx-x64' || 'win-x64' }} --self-contained true -o ./publish/wdrop-${{ matrix.os }}

      - name: Zip artifact
        if: matrix.os != 'windows-latest'
        run: |
          cd publish
          zip -r wdrop-${{ matrix.os }}.zip wdrop-${{ matrix.os }}

      - name: Zip artifact
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $source = "publish/wdrop-${{ matrix.os }}"
          $dest = "publish/wdrop-${{ matrix.os }}.zip"
          Compress-Archive -Path $source/* -DestinationPath $dest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wdrop-${{ matrix.os }}
          path: ./publish/wdrop-${{ matrix.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: publish

      - name: Display structure
        run: ls -R publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}